#!/bin/bash

# pcrontab [-u user] {-l | -r | -e} 
# -l display the pcrontab of the specified user
# -r remove the pcrontab of the specified user
# -e edit the pcrontab of the specified user

# Check if the user is root
#if [ $(id -u) -ne 0 ]; then
#    echo "You must be root to run this script."
#    exit 1
#fi

# Parse the command line arguments
if [ "$1" = "-u" ]; then
    user=$2
    option=$3
else
    user=$(whoami)
    option=$1
fi

# Check if the user exists
if ! id -u $user &>/dev/null; then
    echo "The specified user does not exist."
    exit 2
fi

# The crontab file
file=/etc/pcron/pcrontab$user

# Display the pcrontab
# Check if the pcron file exists
if [ "$option" = "-l" ]; then
    if [ ! -e $file ]; then
        echo "The pcrontab file does not exist."
        exit 3
    else
        cat $file
        exit 0
    fi
fi

# Remove the pcrontab
if [ "$option" = "-r" ]; then
    if [ ! -e $file ]; then
        echo "The pcrontab file does not exist."
        exit 3
    fi
    #Confirmation before removing the file
    echo "Are you sure you want to remove the pcrontab file? (y/n)"
    read answer
    if [ "$answer" != "y" ]; then
        echo "The pcrontab file was not removed."
        exit 4
    fi
    sudo rm $file
    exit 0
fi

# Edit the pcrontab
if [ "$option" = "-e" ]; then
    if [ -e $file ]; then
        sudo cp $file /tmp/pcrontab$user
        chmod 600 /tmp/pcrontab$user

    vi /tmp/pcrontab$user
    #on save move the file to the correct location
    if [ -e /tmp/pcrontab$user ]; then
        
        sudo mv /tmp/pcrontab$user $file
        sudo rm /tmp/pcrontab$user
    fi
    exit 0
fi

